import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConnectedStars from "@/app/Components/BackgroundParticles";
import Navbarhelper from "./Hooks/Navbarhelper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500&display=swap');
          @import url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap');
        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >

        <ConnectedStars />
        <div className="relative z-10">
          <Navbarhelper>

            {children}
          </Navbarhelper>

        </div>


      </body>
    </html >
  );
}

